import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Enumeration;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Clase Main_Frame
 * @author Pedro Miguel Carmona, Ruben Marin Lucas
 */
@SuppressWarnings("serial")
public class Main_Frame extends javax.swing.JFrame {

    /**
    * Creates new form Main_Frame
     */
    public Main_Frame() {

    	 try { UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); }
    	 catch (UnsupportedLookAndFeelException e) { e.getMessage();}
    	 catch (ClassNotFoundException e) { e.getMessage();}
    	 catch (InstantiationException e) {e.getMessage();}
    	 catch (IllegalAccessException e) {e.getMessage(); }


    	initComponents();
        setSize(500, 500);
        setTitle("Proyecto IASI 2019/2020");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);        
        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("unex.png"));
        setIconImage(img.getImage());
        ocultarAEstrella();
        setVisible(true);
    }

    /**
     * Mira cual es el JRadioButton seleccionado en el JGroupButtom
     * @return JRadioButton seleccionado por el usuario    
     */
    private JRadioButton getRadioSelect(){
       for (@SuppressWarnings("rawtypes")
	Enumeration e=buttonGroup1.getElements(); e.hasMoreElements(); )
        {
            JRadioButton b = (JRadioButton)e.nextElement();
            if (b.getModel() == buttonGroup1.getSelection())
            {
                return b;
            }
        }

        return null;
    }
    
    /**
     * Metodo para ocultar los componentes de el algoritmo A*
     */
    private void ocultarAEstrella() {
    	
    	pesoHeuristica.setVisible(false);
    	pesoHeuristicaDato.setVisible(false);
    	pesoCoste.setVisible(false);
    	pesoCosteDato.setVisible(false);
    	
    }
    
    /**
     * Metodo para mostrar los componentes del algoritmo A*
     */
    private void mostrarAEstrella() {

    	pesoHeuristica.setVisible(true);
    	pesoHeuristicaDato.setVisible(true);
    	pesoCoste.setVisible(true);
    	pesoCosteDato.setVisible(true);
    }
    

    /**
     * del puzzle seleccionado se carga del fichero y se almacena en un gestorSolucion
     * @param puzzle puzzle seleccionado por el usuario
     * @return GestorSolucion cargado con el puzzle seleccionado
     */
    private GestorSolucion getPuzzle(String puzzle){
    	GestorSolucion g = new GestorSolucion();
        new InitData(g, puzzle);
        return g;
    }

    /**
     * Devuelve la solucion al puzzle seleccionado por el usuario, por el metodo elegido
     * @param g GestorSolucion con el puzzle elegido 
     * @param algoritmo metodo a resolver el puzzle elegido
     * @return true en caso de haber hallado una solucion al puzzle, false en caso contrario
     */
    private boolean getSolucion(GestorSolucion g, String algoritmo, double pesoHeuristica, double pesoCoste) {

    	boolean fin = false;
    	
    	if(algoritmo.equals(jRadioButton1.getText())) fin = g.escaladaSimple();
    	if(algoritmo.equals(jRadioButton2.getText())) fin = g.escaladaMaximaPendiente();
    	if(algoritmo.equals(jRadioButton3.getText())) fin = g.algoritmoA(pesoHeuristica,pesoCoste);
    	if(algoritmo.equals(jRadioButton4.getText())) fin = g.escaladaMaximaPendiente1();
    	
    	return fin;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SeleccioneNivel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SeleccioneNivel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pesoHeuristicaDato = new javax.swing.JTextField();
        pesoHeuristica = new javax.swing.JLabel();
        pesoCosteDato = new javax.swing.JTextField();
        pesoCoste = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();

        jLabel1.setText("jLabel1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        SeleccioneNivel.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        SeleccioneNivel.setForeground(new java.awt.Color(255, 255, 255));
        SeleccioneNivel.setText("Seleccione nivel:");
        SeleccioneNivel.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(SeleccioneNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SeleccioneNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        SeleccioneNivel1.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        SeleccioneNivel1.setForeground(new java.awt.Color(255, 255, 255));
        SeleccioneNivel1.setText("Seleccione modo resolución:");
        SeleccioneNivel1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(SeleccioneNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeleccioneNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
        		"Puzzle 1 (4x4)", 
        		"Puzzle 2 (4x4)", 
        		"Puzzle 3 (4x4)", 
        		"Puzzle 4 (4x4)", 
        		"Puzzle 5 (4x4)", 
        		"Puzzle 6 (4x4)", 
        		"Puzzle 7 (4x4)", 
        		"Puzzle 8 (4x4)", 
        		"Puzzle 9 (4x4)", 
        		"Puzzle 10 (4x4)",
        		"Puzzle 11 (5x5)", 
        		"Puzzle 12 (5x5)",
        		"Puzzle 13 (6x6)",
        		"Puzzle 14 (7x7)",
        		"Puzzle 15 (8x8)"
        }));
        jComboBox1.setToolTipText("");
        jComboBox1.setBorder(null);
        jComboBox1.setKeySelectionManager(null);
        jComboBox1.setLightWeightPopupEnabled(false);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START");
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });


        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRadioButton1.setText("Escalada Simple");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarAEstrella();
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRadioButton2.setText("Escalada Máxima Pendiente");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarAEstrella();
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRadioButton3.setText("Algoritmo A*");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarAEstrella();
            }
        });
        
        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRadioButton4.setText("Modificación Escalada Máxima Pendiente");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarAEstrella();
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setIcon(new ImageIcon(getClass().getClassLoader().getResource("info_icon.png")));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	jToggleButtom1MouseClicked(evt);
            }
        });

        pesoHeuristicaDato.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        pesoHeuristicaDato.setText("1.6");
        pesoHeuristicaDato.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pesoHeuristicaDato.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
               String value = pesoHeuristicaDato.getText(); // valor que tiene
               if (ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9' || ke.getKeyChar() == KeyEvent.VK_PERIOD) {
            	   pesoHeuristicaDato.setEditable(true);
            	   pesoHeuristicaDato.setText(value);
               }else if(ke.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            	   pesoHeuristicaDato.setEditable(true);
            	  value = value.substring(0, value.length());
            	  pesoHeuristicaDato.setText("");
            	  pesoHeuristicaDato.setText(value);
               }else if(ke.getKeyChar() == KeyEvent.VK_DELETE){
            	   pesoHeuristicaDato.setEditable(true);
            	   pesoHeuristicaDato.setText("");
               }else {
            	   pesoHeuristicaDato.setEditable(false);
               }
            }
         });

        pesoHeuristica.setBackground(new java.awt.Color(255, 255, 255));
        pesoHeuristica.setFont(new java.awt.Font("Roboto Bk", 0, 11)); // NOI18N
        pesoHeuristica.setText("Peso heuristica:");

        pesoCosteDato.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        pesoCosteDato.setText("0.4");
        pesoCosteDato.setToolTipText("");
        pesoCosteDato.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {            	
               String value = pesoCosteDato.getText(); // valor que tiene
               if (ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9' || ke.getKeyChar() == KeyEvent.VK_PERIOD) {
                  pesoCosteDato.setEditable(true);
                  pesoCosteDato.setText(value);
               }else if(ke.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            	  pesoCosteDato.setEditable(true);
            	  value = value.substring(0, value.length());
            	  pesoCosteDato.setText("");
            	  pesoCosteDato.setText(value);
               }else if(ke.getKeyChar() == KeyEvent.VK_DELETE){
            	  pesoCosteDato.setEditable(true);
            	  pesoCosteDato.setText("");
               }
               else {
                  pesoCosteDato.setEditable(false);
               }
            }
         });


        pesoCoste.setBackground(new java.awt.Color(255, 255, 255));
        pesoCoste.setFont(new java.awt.Font("Roboto Bk", 0, 11)); // NOI18N
        pesoCoste.setText("Peso coste:");

        jLayeredPane1.setLayer(pesoHeuristicaDato, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pesoHeuristica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pesoCosteDato, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pesoCoste, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0,0,0)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesoHeuristica, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoCosteDato, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoHeuristicaDato, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(0, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesoHeuristica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pesoHeuristicaDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5,5,5)
                .addComponent(pesoCoste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoCosteDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0,0,0))
        );



        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButton2)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jRadioButton3))
                        .addContainerGap(262, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(126, 126, 126))))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para saber si la cadena introducida se podria pasar a double
     * @param cadena cadena a comprobar
     * @return true si se puede pasar o false en caso contrario
     */
    private static boolean isDouble(String cadena){
    	try {
    		Double.parseDouble(cadena);
    		return true;
    	} catch (NumberFormatException nfe){
    		return false;
    	}
    }
    
    
    
    /***
     * Accion al pulsar el boton START
     * @param evt evento de haber pulsado el boton
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    	String s = "";
    	boolean mensaje = false;
    	double pesoHeuristica = 1.4, pesoCoste = 0.6;

    	if(!isDouble(pesoHeuristicaDato.getText())){
    		s += "\n - El peso de la heuristica introducido no es correcto\n\n";
    		mensaje = true;
    	}else {
    		pesoHeuristica = Double.parseDouble(pesoHeuristicaDato.getText());
    	}
    	
    	
    	if(!isDouble(pesoCosteDato.getText())) {
    		s += " - El peso del coste introducido no es correcto\n\n";
    		mensaje = true;
    	}else {
    		pesoCoste = Double.parseDouble(pesoCosteDato.getText());
    	}
    	
    	if(!mensaje) {
    		dispose();
        	GestorSolucion g = getPuzzle(jComboBox1.getSelectedItem().toString());
            boolean resuelto = getSolucion(g, getRadioSelect().getText(), pesoHeuristica, pesoCoste);
            new Solucion_Frame(g,jComboBox1.getSelectedItem().toString(), getRadioSelect().getText(), resuelto, pesoHeuristica, pesoCoste);
    	}else {
    		JOptionPane optionPane = new JOptionPane(s, JOptionPane.ERROR_MESSAGE);
    		Image img = new ImageIcon(getClass().getClassLoader().getResource("unex.png")).getImage();
    		JDialog dialog = optionPane.createDialog("Error en los pesos introducidos");
    		dialog.setIconImage(img);
    		dialog.setAlwaysOnTop(true);
    		dialog.setVisible(true);
    	}
    	


    }//GEN-LAST:event_jButton1MouseClicked
    
    
    /***
     * Accion al pulsar el boton de informacion
     * @param evt evento de haber pulsado el boton
     */
    private void jToggleButtom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    	new Info_Frame();
    }//GEN-LAST:event_jButton1MouseClicked
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SeleccioneNivel;
    private javax.swing.JLabel SeleccioneNivel1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel pesoHeuristica;
    private javax.swing.JLabel pesoCoste;
    private javax.swing.JTextField pesoHeuristicaDato;
    private javax.swing.JTextField pesoCosteDato;
    // End of variables declaration//GEN-END:variables
}
